package main

type TokenType string

const (
	LEFT_PAREN = "LEFT_PAREN"
	RIGHT_PAREN = "RIGHT_PAREN"
	PLUS = "PLUS"
	NUMBER = "NUMBER"
	MINUS = "MINUS"
	TIMES = "TIMES"
	DIVIDE = "DIVIDE"
	STRING = "STRING"
	LIST = "LIST"
	CONS = "CONS"
	FIRST = "FIRST"
	LESS_THAN = "LESS_THAN"
	GREATER_THAN = "GREATER_THAN"
	EQUAL = "EQUAL"
	IF = "IF"
	AND = "AND"
	OR = "OR"
	TRUE = "TRUE"
	FALSE = "FALSE"
	LESS_THAN_EQUAL = "LESS_THAN_EQUAL"
	GREATER_THAN_EQUAL = "GREATER_THAN_EQUAL"
	DEFINE = "DEFINE"
	SYMBOL = "SYMBOL"
	MOD = "MOD"
	CDR = "CDR"
	LENGTH = "LENGTH"
	EQUALS = "EQUALS"

)


